spring:
  application:
    name: yum-auth-server

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/auth/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  enable-spring-security: false
